Data:
  data_root: ../data/MSCOCO2014                      # 数据路径
  base_data_root: ../data/base_annotation/coco/      # 基础路径
  train_list: ../CFENet/lists/coco/train.txt                 # 训练集图像集名称
  val_list: ../CFENet/lists/coco/val.txt                     # 测试集图像名称
  classes: 2                                         # 二分类，用于掩码计算指标


Train:
  # Aug
  train_h: 641                                       # 图像重转换后的宽高
  train_w: 641
  down_h: 81
  down_w: 81
  val_size: 641                                      # 验证阶段的图像高宽
  scale_min: 0.8  # minimum random scale             # 图像缩放缩放尺度
  scale_max: 1.25 # maximum random scale
  rotate_min: -10  # minimum random rotate           # 图像旋转度数
  rotate_max: 10  # maximum random rotate
  ignore_label: 255                                  # 边缘像素和填充值像素大小
  padding_label: 255
  # Dataset & Mode
  split: 3                                           # 指明验证的数据子集
  shot: 1                                            # 1shot学习
  data_set: 'coco'                                   # 数据集名称
  use_split_coco: True # True means FWB setting      # 是否使用coco数据集类别的交叉分组
  # Optimizer
  batch_size: 2 # batch size for training (bs8 for 1GPU)        # 训练阶段的批量大小
  base_lr: 0.001                                                # 基础的学习率
  epochs: 50                                                    # 需要循环的epoch数
  start_epoch: 0                                                # 启示epoch
  stop_interval: 75 # stop when the best result is not updated for "stop_interval" epochs
  index_split: -1 # index for determining the params group with 10x learning rate
  power: 0.9 # 0 means no decay                                 优化器参数设置
  momentum: 0.9
  weight_decay: 0.0001
  warmup: False
  # Viz & Save & Resume
  print_freq: 10                                               # 打印频率
  save_freq: 5                                                 # 保存频率
  resume: none # path to latest checkpoint (default: none, such as epoch_10.pth)     保存路径
  snapshot_path: 
  result_path: 
  # Validate
  evaluate: True                                               # 是否进行验证
  SubEpoch_val: True # val at the half epoch
  fix_random_seed_val: True
  batch_size_val: 1                                           # 验证阶段的批量数
  resized_val: True
  ori_resize: True  # use original label for evaluation       是否在验证阶段也使用原掩码图尺寸
  # Else
  workers: 8                                                  # 数据加载时使用的num_workers
  fix_bn: True                                                # 是否冻结BN参数
  manual_seed: 321                                            # 随机数种子
  seed_deterministic: False
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  
Method:
  layers: 50                                                  # 骨干网络的层数
  vgg: False                                                  # 是否使用vgg
  aux_weight1: 1.0
  aux_weight2: 1.0
  low_fea: 'layer2'  # low_fea for computing the Gram matrix
  kshot_trans_dim: 2 # K-shot dimensionality reduction
  merge: 'final'     # fusion scheme for GFSS ('base' Eq(S1) | 'final' Eq(18) )
  merge_tau: 0.9     # fusion threshold tau

Test_Finetune:
  weight: # load weight for fine-tuning or testing (such as train5_epoch_47.5_0.4926.pth)
  ann_type: 'mask' # mask/bbox
  log_dir: /root/autodl-tmp/my_work/BAM/result


